### ISSUE TITLE
Incorrect longitude limits in V2.0 and v2.1 PVOL csv files

### ISSUE THREAD

**Issue by msimpson-mo** [meriladislav/odimh5_validator#1]
Hi,

When using the validator to check data against ODIM v2.1 I get the following file failure notification:

> WARNING - INCORRECT VALUE - mandatory entry "/where/lon" with value "-6.338889" doesn`t match the ">=0.0&&<=90.0" assumed value.
> WARNING - NON-COMPLIANT FILE - file <file_name> IS NOT a standard-compliant ODIM-H5 file - see the previous WARNING messages

This is incorrectly reporting the file as invalid, it seems the limits are inaccurate (unless I've missed something in the ODIM specification).  

There are two csv files, [ODIM_H5_V2_0_PVOL.csv](../blob/9b6fb499f29e3732c6b23a3c0a5edb56f45a3a5d/data/ODIM_H5_V2_0_PVOL.csv#L11) and  [ODIM_H5_V2_1_PVOL.csv](../blob/9b6fb499f29e3732c6b23a3c0a5edb56f45a3a5d/data/ODIM_H5_V2_1_PVOL.csv#L11), which have limits on the `/where/lon` attribute set to `>=0.0&&<=90.0`. This seems incorrect, I would assume it should be `>-180.0&&<=180.0`.

Similarly, the [`/where/lat`](../blob/9b6fb499f29e3732c6b23a3c0a5edb56f45a3a5d/data/ODIM_H5_V2_0_PVOL.csv#L12) in the [ODIM_H5_V2_0_PVOL.csv](../blob/9b6fb499f29e3732c6b23a3c0a5edb56f45a3a5d/data/ODIM_H5_V2_0_PVOL.csv) definition has a limit of `>=0.0&&<=90.0`, I would assume this should be `>-90.0&&<=90.0`.

There are no other such limits for `/where/lon` and `/where/lat` in the other CSV files.

Please can the limits be updated or removed?

**Comment by meriladislav** [comment]
Hi!

Thanks for the report! You` re right. I changed the limits in all tables to -180,180 and -90,90.

**Comment by msimpson-mo** [comment]
Thank you. I can confirm the updated CSV files for v2.1 no longer show the data in question as "NON-COMPLIANT FILE".

**Comment by meriladislav** [comment]
Thanks!
